[global]

# Global settings
developmentMode = false

[logger]

# Logger settings
level = "info"

[client]

# Client settings
caching = true
displayEnabled = true
showErrorDetails = false

[runner]

# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true

[server]

# Server settings
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
enableStaticServing = true
runOnSave = false
allowRunOnSave = false
fileWatcherType = "auto"
cookieSecret = ""

[browser]

# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]

# Theme settings
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[deprecation]

# Deprecation warnings
showPyplotGlobalUse = false
